[project]
name = "Part_III_Project"
version = "0.1.0"
description = ""
requires-python = ">=3.14"
readme = "README.md"
authors = [
  { name = "Thomas Holland", email = "101332229+0thomasholland@users.noreply.github.com" },
]
# Core dependencies for the project to run
dependencies = [
  "matplotlib",
  "mpltern",
  "numpy",
  "pandas",
  "pygeoinf==1.3.9",
  "pyslfp==1.1.4",
  "statsmodels",
  "ty",
  "pynvim",
  "copernicusmarine>=2.3.0,<3.0.0",
  "xarray>=2026.1.0,<2027.0.0",
  "netcdf4>=1.7.4,<2.0.0",
  "h5py>=3.15.1,<4.0.0",
  "colorcet>=3.1.0,<4.0.0",
  "dill>=0.4.1,<0.5.0",
  "pygmt>=0.18.0,<0.19.0",
  "seaborn>=0.13.2,<0.14.0",
]

[dependency-groups]
# Tools for development, notebooks, and linting
dev = [
  "jupyter",
  "ipykernel",
  "jupytext",
  "jupyter-client",
  "notebook",
  "ruff",
]

[build-system]
requires = ["uv-build>=0.1"]
build-backend = "uv_build"

[tool.uv]
package = true

[tool.uv.build-backend]
module-name = ["project", "pygeoinf_extras", "pyslfp_extras"]

[tool.ruff]
line-length = 60
src = ["src"]

[tool.ruff.lint]
select = ["F", "E", "W", "I", "B", "UP", "SIM", "N"]
extend-select = ["ANN", "TID", "RUF", "S", "ARG", "PTH", "C4", "RET", "PT"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["ANN201", "ANN204"]
"tests/*" = ["ANN"]

[tool.ty]
python-version = "3.14"
exclude = [
    ".venv",
    ".git",
    "outputs"
]
