[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "Part_III_Project"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = "~=3.12.0"
authors = [
    { name = "Thomas Holland", email = "101332229+0thomasholland@users.noreply.github.com" },
]
dependencies = [
    "matplotlib",
    "mpltern",
    "numpy",
    "pandas",
    "pyslfp",
]

[project.optional-dependencies]
dev = [
    "ipykernel",
    "jupytext",
    "ruff",
    "statsmodels",
    "ty",
]

[tool.poetry]
packages = [{ include = "Part_III_Project", from = "src" }]

[tool.ruff]
target-version = "py312"
line-length = 88
src = ["src"]

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "ANN",
    "TID",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["ANN201", "ANN204"]

[tool.ty]
implicit-optional = true
src = ["src"]
